version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 3306:3306
    command:
      - --disable-partition-engine-check
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./web_data1:/app
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 8000:8000
    depends_on:
      - db